development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  databse: db/test.sqlite3


#adapter: mysql2
#host: test-mysql
#port: 3306
#username: root
#password: mypassword
#databse: users